syntax = "proto3";

package gonetconfig;

option go_package = "github.com/amb1s1/gonetconfig/proto";

message Device {
    string name = 1;
    Vendor vendor = 2;
    Model model = 3;
    OS os = 4; 
}

enum ConfigGenType {
    CGT_FULL = 0;
    CGT_PARTIAL = 1;
}

enum Vendor {
    VD_UNKNOW = 0;
    VD_CISCO = 1;
    VD_CISCOXR = 2;
    VD_JUNIPER = 3;
    VD_ARISTA = 4;
}

enum Model {
    MD_UNKNOW = 0;
}

enum OS {
    OS_UNKNOW = 0;
}

message ConfigFeature {
	string name = 1;
	int32 version = 2;
	string configuration = 3;
}

message ConfigGenRequest {
    ConfigGenType config_gen_type = 1;
    Device device = 2;
}

message ConfigGenResponse {
    string status = 1;
    repeated ConfigFeature config_feature = 2; 
}
service GoNetConfigService {
    rpc GetConfigGen(ConfigGenRequest) returns (ConfigGenResponse);
}
