// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: proto/service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GoNetConfigService_GetConfigGen_FullMethodName = "/gonetconfig.GoNetConfigService/GetConfigGen"
)

// GoNetConfigServiceClient is the client API for GoNetConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoNetConfigServiceClient interface {
	GetConfigGen(ctx context.Context, in *ConfigGenRequest, opts ...grpc.CallOption) (*ConfigGenResponse, error)
}

type goNetConfigServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGoNetConfigServiceClient(cc grpc.ClientConnInterface) GoNetConfigServiceClient {
	return &goNetConfigServiceClient{cc}
}

func (c *goNetConfigServiceClient) GetConfigGen(ctx context.Context, in *ConfigGenRequest, opts ...grpc.CallOption) (*ConfigGenResponse, error) {
	out := new(ConfigGenResponse)
	err := c.cc.Invoke(ctx, GoNetConfigService_GetConfigGen_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoNetConfigServiceServer is the server API for GoNetConfigService service.
// All implementations must embed UnimplementedGoNetConfigServiceServer
// for forward compatibility
type GoNetConfigServiceServer interface {
	GetConfigGen(context.Context, *ConfigGenRequest) (*ConfigGenResponse, error)
	mustEmbedUnimplementedGoNetConfigServiceServer()
}

// UnimplementedGoNetConfigServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGoNetConfigServiceServer struct {
}

func (UnimplementedGoNetConfigServiceServer) GetConfigGen(context.Context, *ConfigGenRequest) (*ConfigGenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfigGen not implemented")
}
func (UnimplementedGoNetConfigServiceServer) mustEmbedUnimplementedGoNetConfigServiceServer() {}

// UnsafeGoNetConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoNetConfigServiceServer will
// result in compilation errors.
type UnsafeGoNetConfigServiceServer interface {
	mustEmbedUnimplementedGoNetConfigServiceServer()
}

func RegisterGoNetConfigServiceServer(s grpc.ServiceRegistrar, srv GoNetConfigServiceServer) {
	s.RegisterService(&GoNetConfigService_ServiceDesc, srv)
}

func _GoNetConfigService_GetConfigGen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigGenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoNetConfigServiceServer).GetConfigGen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoNetConfigService_GetConfigGen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoNetConfigServiceServer).GetConfigGen(ctx, req.(*ConfigGenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GoNetConfigService_ServiceDesc is the grpc.ServiceDesc for GoNetConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoNetConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gonetconfig.GoNetConfigService",
	HandlerType: (*GoNetConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfigGen",
			Handler:    _GoNetConfigService_GetConfigGen_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}
