// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/service.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConfigGenType int32

const (
	ConfigGenType_CGT_FULL    ConfigGenType = 0
	ConfigGenType_CGT_PARTIAL ConfigGenType = 1
)

var ConfigGenType_name = map[int32]string{
	0: "CGT_FULL",
	1: "CGT_PARTIAL",
}

var ConfigGenType_value = map[string]int32{
	"CGT_FULL":    0,
	"CGT_PARTIAL": 1,
}

func (x ConfigGenType) String() string {
	return proto.EnumName(ConfigGenType_name, int32(x))
}

func (ConfigGenType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{0}
}

type Vendor int32

const (
	Vendor_VD_UNKNOW  Vendor = 0
	Vendor_VD_CISCO   Vendor = 1
	Vendor_VD_CISCOXR Vendor = 2
	Vendor_VD_JUNIPER Vendor = 3
	Vendor_VD_ARISTA  Vendor = 4
)

var Vendor_name = map[int32]string{
	0: "VD_UNKNOW",
	1: "VD_CISCO",
	2: "VD_CISCOXR",
	3: "VD_JUNIPER",
	4: "VD_ARISTA",
}

var Vendor_value = map[string]int32{
	"VD_UNKNOW":  0,
	"VD_CISCO":   1,
	"VD_CISCOXR": 2,
	"VD_JUNIPER": 3,
	"VD_ARISTA":  4,
}

func (x Vendor) String() string {
	return proto.EnumName(Vendor_name, int32(x))
}

func (Vendor) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{1}
}

type Model int32

const (
	Model_MD_UNKNOW  Model = 0
	Model_MD_C3560CX Model = 1
)

var Model_name = map[int32]string{
	0: "MD_UNKNOW",
	1: "MD_C3560CX",
}

var Model_value = map[string]int32{
	"MD_UNKNOW":  0,
	"MD_C3560CX": 1,
}

func (x Model) String() string {
	return proto.EnumName(Model_name, int32(x))
}

func (Model) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{2}
}

type OS int32

const (
	OS_OS_UNKNOW OS = 0
)

var OS_name = map[int32]string{
	0: "OS_UNKNOW",
}

var OS_value = map[string]int32{
	"OS_UNKNOW": 0,
}

func (x OS) String() string {
	return proto.EnumName(OS_name, int32(x))
}

func (OS) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{3}
}

type Device struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Vendor               Vendor   `protobuf:"varint,2,opt,name=vendor,proto3,enum=gonetconfig.Vendor" json:"vendor,omitempty"`
	Model                Model    `protobuf:"varint,3,opt,name=model,proto3,enum=gonetconfig.Model" json:"model,omitempty"`
	Os                   OS       `protobuf:"varint,4,opt,name=os,proto3,enum=gonetconfig.OS" json:"os,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{0}
}

func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (m *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(m, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Device) GetVendor() Vendor {
	if m != nil {
		return m.Vendor
	}
	return Vendor_VD_UNKNOW
}

func (m *Device) GetModel() Model {
	if m != nil {
		return m.Model
	}
	return Model_MD_UNKNOW
}

func (m *Device) GetOs() OS {
	if m != nil {
		return m.Os
	}
	return OS_OS_UNKNOW
}

type ConfigFeature struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              int32    `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Configuration        string   `protobuf:"bytes,3,opt,name=configuration,proto3" json:"configuration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigFeature) Reset()         { *m = ConfigFeature{} }
func (m *ConfigFeature) String() string { return proto.CompactTextString(m) }
func (*ConfigFeature) ProtoMessage()    {}
func (*ConfigFeature) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{1}
}

func (m *ConfigFeature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigFeature.Unmarshal(m, b)
}
func (m *ConfigFeature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigFeature.Marshal(b, m, deterministic)
}
func (m *ConfigFeature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigFeature.Merge(m, src)
}
func (m *ConfigFeature) XXX_Size() int {
	return xxx_messageInfo_ConfigFeature.Size(m)
}
func (m *ConfigFeature) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigFeature.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigFeature proto.InternalMessageInfo

func (m *ConfigFeature) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ConfigFeature) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ConfigFeature) GetConfiguration() string {
	if m != nil {
		return m.Configuration
	}
	return ""
}

type ConfigGenRequest struct {
	ConfigGenType        ConfigGenType `protobuf:"varint,1,opt,name=config_gen_type,json=configGenType,proto3,enum=gonetconfig.ConfigGenType" json:"config_gen_type,omitempty"`
	Device               *Device       `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ConfigGenRequest) Reset()         { *m = ConfigGenRequest{} }
func (m *ConfigGenRequest) String() string { return proto.CompactTextString(m) }
func (*ConfigGenRequest) ProtoMessage()    {}
func (*ConfigGenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{2}
}

func (m *ConfigGenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigGenRequest.Unmarshal(m, b)
}
func (m *ConfigGenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigGenRequest.Marshal(b, m, deterministic)
}
func (m *ConfigGenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigGenRequest.Merge(m, src)
}
func (m *ConfigGenRequest) XXX_Size() int {
	return xxx_messageInfo_ConfigGenRequest.Size(m)
}
func (m *ConfigGenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigGenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigGenRequest proto.InternalMessageInfo

func (m *ConfigGenRequest) GetConfigGenType() ConfigGenType {
	if m != nil {
		return m.ConfigGenType
	}
	return ConfigGenType_CGT_FULL
}

func (m *ConfigGenRequest) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

type ConfigGenResponse struct {
	Status               string           `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ConfigFeature        []*ConfigFeature `protobuf:"bytes,2,rep,name=config_feature,json=configFeature,proto3" json:"config_feature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ConfigGenResponse) Reset()         { *m = ConfigGenResponse{} }
func (m *ConfigGenResponse) String() string { return proto.CompactTextString(m) }
func (*ConfigGenResponse) ProtoMessage()    {}
func (*ConfigGenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{3}
}

func (m *ConfigGenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigGenResponse.Unmarshal(m, b)
}
func (m *ConfigGenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigGenResponse.Marshal(b, m, deterministic)
}
func (m *ConfigGenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigGenResponse.Merge(m, src)
}
func (m *ConfigGenResponse) XXX_Size() int {
	return xxx_messageInfo_ConfigGenResponse.Size(m)
}
func (m *ConfigGenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigGenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigGenResponse proto.InternalMessageInfo

func (m *ConfigGenResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ConfigGenResponse) GetConfigFeature() []*ConfigFeature {
	if m != nil {
		return m.ConfigFeature
	}
	return nil
}

func init() {
	proto.RegisterEnum("gonetconfig.ConfigGenType", ConfigGenType_name, ConfigGenType_value)
	proto.RegisterEnum("gonetconfig.Vendor", Vendor_name, Vendor_value)
	proto.RegisterEnum("gonetconfig.Model", Model_name, Model_value)
	proto.RegisterEnum("gonetconfig.OS", OS_name, OS_value)
	proto.RegisterType((*Device)(nil), "gonetconfig.Device")
	proto.RegisterType((*ConfigFeature)(nil), "gonetconfig.ConfigFeature")
	proto.RegisterType((*ConfigGenRequest)(nil), "gonetconfig.ConfigGenRequest")
	proto.RegisterType((*ConfigGenResponse)(nil), "gonetconfig.ConfigGenResponse")
}

func init() {
	proto.RegisterFile("proto/service.proto", fileDescriptor_c33392ef2c1961ba)
}

var fileDescriptor_c33392ef2c1961ba = []byte{
	// 487 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0x5d, 0x6f, 0xda, 0x30,
	0x14, 0x6d, 0x42, 0x61, 0xeb, 0xa5, 0x40, 0x66, 0xa4, 0x29, 0xaa, 0xb4, 0x0d, 0xb1, 0x0f, 0x21,
	0x26, 0xc1, 0x4a, 0xb5, 0xbd, 0xa7, 0x61, 0x8d, 0xd8, 0x80, 0x54, 0x4e, 0x60, 0xd5, 0x5e, 0xa2,
	0x10, 0x5c, 0x86, 0x34, 0x6c, 0x16, 0x3b, 0x48, 0x7d, 0xde, 0x5f, 0xd8, 0x0f, 0x9e, 0x62, 0x3b,
	0x15, 0x4c, 0xec, 0x09, 0xce, 0xbd, 0xe7, 0x5c, 0x1f, 0x9f, 0xeb, 0x40, 0x73, 0x9b, 0x32, 0xc1,
	0xfa, 0x9c, 0xa4, 0xbb, 0x75, 0x42, 0x7a, 0x12, 0xa1, 0xea, 0x8a, 0x51, 0x22, 0x12, 0x46, 0xef,
	0xd7, 0xab, 0xf6, 0x1f, 0x03, 0x2a, 0x43, 0x92, 0x77, 0x11, 0x82, 0x53, 0x1a, 0x6f, 0x88, 0x6d,
	0xb4, 0x8c, 0xce, 0x19, 0x96, 0xff, 0xd1, 0x7b, 0xa8, 0xec, 0x08, 0x5d, 0xb2, 0xd4, 0x36, 0x5b,
	0x46, 0xa7, 0x3e, 0x68, 0xf6, 0xf6, 0xc4, 0xbd, 0xb9, 0x6c, 0x61, 0x4d, 0x41, 0x1d, 0x28, 0x6f,
	0xd8, 0x92, 0xfc, 0xb4, 0x4b, 0x92, 0x8b, 0x0e, 0xb8, 0x93, 0xbc, 0x83, 0x15, 0x01, 0xbd, 0x02,
	0x93, 0x71, 0xfb, 0x54, 0xd2, 0x1a, 0x07, 0x34, 0x3f, 0xc0, 0x26, 0xe3, 0xed, 0x04, 0x6a, 0xae,
	0x2c, 0xdc, 0x90, 0x58, 0x64, 0xe9, 0x71, 0x73, 0x36, 0x3c, 0xd9, 0x91, 0x94, 0xaf, 0x19, 0x95,
	0xee, 0xca, 0xb8, 0x80, 0xe8, 0x0d, 0xd4, 0xd4, 0xbc, 0x2c, 0x8d, 0x45, 0xde, 0x2f, 0x49, 0xd9,
	0x61, 0xb1, 0xfd, 0xdb, 0x00, 0x4b, 0x9d, 0xe2, 0x11, 0x8a, 0xc9, 0xaf, 0x8c, 0x70, 0x81, 0xae,
	0xa1, 0xa1, 0x58, 0xd1, 0x8a, 0xd0, 0x48, 0x3c, 0x6c, 0xd5, 0x99, 0xf5, 0xc1, 0xc5, 0x81, 0xcf,
	0x47, 0x5d, 0xf8, 0xb0, 0x25, 0xc5, 0x60, 0x0d, 0xf3, 0xd4, 0x96, 0x32, 0x53, 0xe9, 0xab, 0xfa,
	0x4f, 0x6a, 0x2a, 0x6e, 0xac, 0x29, 0x6d, 0x0a, 0xcf, 0xf6, 0x4c, 0xf0, 0x2d, 0xa3, 0x9c, 0xa0,
	0xe7, 0x50, 0xe1, 0x22, 0x16, 0x19, 0xd7, 0x17, 0xd6, 0x08, 0x39, 0x50, 0xd7, 0xee, 0xee, 0x55,
	0x30, 0xb6, 0xd9, 0x2a, 0x75, 0xaa, 0x47, 0xcd, 0xe9, 0xe8, 0x0a, 0x73, 0x1a, 0x76, 0x7b, 0x45,
	0xb4, 0x85, 0xdb, 0x73, 0x78, 0xea, 0x7a, 0x61, 0x74, 0x33, 0x1b, 0x8f, 0xad, 0x13, 0xd4, 0x80,
	0x6a, 0x8e, 0x6e, 0x1d, 0x1c, 0x8e, 0x9c, 0xb1, 0x65, 0x74, 0x43, 0xa8, 0xa8, 0x3d, 0xa3, 0x1a,
	0x9c, 0xcd, 0x87, 0xd1, 0x6c, 0xfa, 0x75, 0xea, 0x7f, 0xb3, 0x4e, 0x72, 0xdd, 0x7c, 0x18, 0xb9,
	0xa3, 0xc0, 0xf5, 0x2d, 0x03, 0xd5, 0x01, 0x0a, 0x74, 0x87, 0x2d, 0x53, 0xe3, 0x2f, 0xb3, 0xe9,
	0xe8, 0xf6, 0x33, 0xb6, 0x4a, 0x5a, 0xec, 0xe0, 0x51, 0x10, 0x3a, 0xd6, 0x69, 0xf7, 0x1d, 0x94,
	0xe5, 0x8b, 0xc8, 0xeb, 0x93, 0xbd, 0xa1, 0x75, 0x80, 0xc9, 0x30, 0x72, 0xaf, 0x3e, 0x7e, 0xfa,
	0xe0, 0xde, 0x59, 0x46, 0xb7, 0x09, 0xa6, 0x1f, 0xe4, 0x24, 0x3f, 0x78, 0x24, 0x0d, 0x12, 0x40,
	0x1e, 0x9b, 0x12, 0xa1, 0xee, 0x11, 0xa8, 0xd7, 0x8d, 0x26, 0x70, 0xee, 0x15, 0x35, 0x8f, 0x50,
	0xf4, 0xe2, 0xf8, 0xc2, 0xf4, 0xa2, 0x2f, 0x5e, 0xfe, 0xaf, 0xad, 0x56, 0x70, 0xfd, 0xf6, 0xfb,
	0xeb, 0xd5, 0x5a, 0xfc, 0xc8, 0x16, 0xbd, 0x84, 0x6d, 0xfa, 0xf1, 0x66, 0x71, 0xc9, 0x2f, 0xfb,
	0x7b, 0x92, 0xbe, 0xfc, 0x9a, 0x16, 0x15, 0xf9, 0x73, 0xf5, 0x37, 0x00, 0x00, 0xff, 0xff, 0x44,
	0x85, 0x46, 0x54, 0x6b, 0x03, 0x00, 0x00,
}
